### ISSUE TITLE
Notification button shortcode is not working

### ISSUE THREAD

**Issue by anshucedcoss** [Makewebbetter/points-and-rewards-for-woocommerce#120]
Notification button shortcode is not working
![image](https://user-images.githubusercontent.com/25762796/96717688-7d33da00-13c4-11eb-806e-a7526d310d1b.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by anshucedcoss** [comment]
Still having some issue while updatating the page after wrotomg the shortcode
When use shortcode then is should not draggable.
